In [1]:
import os
import pickle
import joblib
import pandas as pd
import numpy as np
import random
import itertools

import matplotlib.pyplot as plt
plt.style.use('tableau-colorblind10')





import sys
sys.path.append('/data/Hydra_Work/Competition_Functions') 
from Processing_Functions import process_forecast_date, process_seasonal_forecasts
from Data_Transforming import read_nested_csvs, generate_daily_flow, use_USGS_flow_data, USGS_to_daily_df_yearly

sys.path.append('/data/Hydra_Work/Pipeline_Functions')
from Folder_Work import filter_rows_by_year, csv_dictionary, add_day_of_year_column, create_dataframe_from_txt

sys.path.append('/data/Hydra_Work/Post_Rodeo_Work/ML_Functions.py')
from Full_LSTM_ML_Functions import Specific_Heads, Google_Model_Block, SumPinballLoss, EarlyStopper, Model_Run, No_Body_Model_Run, Indicator_LSTM_Run, define_models



from datetime import datetime
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim.lr_scheduler as lr_scheduler

# Making the cross validation set

Cross Validation decisions:
- It looks like I only have 10 years right now, and if the results are good I can keep it that way (justify by independent years)
- Training set of 80% and Validation of 20% is fine, makes sense to make the Validation years adjacent instead of random, probably doesn't matter much but adjacent minimises theyre connection with the years in the training dataset
- This means theres only 5 folds which shouldn't take forever to do 
- There's an issue right now where my validation set is also my test set, how much can I get around this?
- I could test a 10-20-10 set up, from the looks of it there won't be that much loss in performance by reducing the training set by 12%? 
- If I assume the years are independent then it doesn't matter which dates I choose for validation years when I've got a specific testing year
- K -fold cross validation means splitting the data in k chunks and choosing a different chunk for each, p-fold involves choosing all possible combinations of size p for the splits

Structure of the folders:
- Can do Validation_Models/Val_Years/Model/.pth, bs Model/Val_Years/.pth
- I think the first makes more sense, I would realy want to ompare models trained over the same years


Restructuring Current code:
- I want to fit this whole thing into a for loop so I can run it
- Alternatively I can have the validation years as a parameter in the config_space and just let the code run as is
- It would be nice to make the prep section smaller visually, or hidden somewhere else

In [2]:
basins = ['libby_reservoir_inflow',  'owyhee_r_bl_owyhee_dam',  'san_joaquin_river_millerton_reservoir',  'taylor_park_reservoir_inflow',
 'boise_r_nr_boise', 'green_r_bl_howard_a_hanson_dam', 'weber_r_nr_oakley', 'detroit_lake_inflow', 'virgin_r_at_virtin', 'dillon_reservoir_inflow',
 'pueblo_reservoir_inflow', 'hungry_horse_reservoir_inflow', 'stehekin_r_at_stehekin', 'pecos_r_nr_pecos', 'snake_r_nr_heise', 'yampa_r_nr_maybell',
 'colville_r_at_kettle_falls', 'missouri_r_at_toston', 'merced_river_yosemite_at_pohono_bridge', 'animas_r_at_durango','fontenelle_reservoir_inflow', 'boysen_reservoir_inflow']

In [3]:
basins = ['libby_reservoir_inflow',  'owyhee_r_bl_owyhee_dam',  'san_joaquin_river_millerton_reservoir',  'taylor_park_reservoir_inflow',
 'boise_r_nr_boise', 'green_r_bl_howard_a_hanson_dam', 'weber_r_nr_oakley', 'detroit_lake_inflow', 'virgin_r_at_virtin', 'dillon_reservoir_inflow',
 'pueblo_reservoir_inflow', 'hungry_horse_reservoir_inflow', 'stehekin_r_at_stehekin', 'pecos_r_nr_pecos', 'snake_r_nr_heise', 'yampa_r_nr_maybell',
 'colville_r_at_kettle_falls', 'missouri_r_at_toston', 'merced_river_yosemite_at_pohono_bridge', 'animas_r_at_durango','fontenelle_reservoir_inflow', 'boysen_reservoir_inflow']

selected_years = range(2000,2024,2)


base_dir = "/data/Hydra_Work/Scaled_Data"

# Define dictionaries and DataFrames
dictionaries = ['era5', 'seasonal_forecasts', 'daily_flow', 'climatological_flows']

dataframes = ['climate_indices', 'clustering_static_variables']

# Function to load dictionaries
def load_dictionaries(base_dir, names):
    loaded_dicts = {}
    for name in names:
        file_path = os.path.join(base_dir, f"{name}.pkl")
        with open(file_path, 'rb') as file:
            locals()[name] = pickle.load(file)
    return locals()

# Function to load DataFrames
def load_dataframes(base_dir, names):
    loaded_dfs = {}
    for name in names:
        file_path = os.path.join(base_dir, f"{name}.pkl")
        locals()[name] = pd.read_pickle(file_path)
    return locals()

saved_dicts = load_dictionaries(base_dir, dictionaries)
saved_dfs = load_dataframes(base_dir, dataframes)

for name in dictionaries:
    locals()[name] = saved_dicts[name]

for name in dataframes:
    locals()[name] = saved_dfs[name]


device = torch.device('cuda' if torch.cuda.
                is_available() else 'cpu')

criterion = SumPinballLoss(quantiles = [0.1, 0.5, 0.9])

basin = 'animas_r_at_durango' 
All_Dates = daily_flow[basin].index[
    ((daily_flow[basin].index.month < 6) | ((daily_flow[basin].index.month == 6) & (daily_flow[basin].index.day < 24))) &
    ((daily_flow[basin].index.year % 2 == 0) | ((daily_flow[basin].index.month > 10) | ((daily_flow[basin].index.month == 10) & (daily_flow[basin].index.day >= 1))))
]
All_Dates = All_Dates[All_Dates.year > 1998]


seed = 42 ; torch.manual_seed(seed) ; random.seed(seed) ; np.random.seed(seed)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

days  = 90

In [4]:
static_variables = clustering_static_variables

# Potential Additional Information to use

In [6]:
# Adding discharge from Animas_Silverton to a new ERA5 dictionary
from sklearn.preprocessing import StandardScaler

Animas_R_at_Silverton_path = '/data/Hydra_Work/HydroBasin_Data/Animas_R_at_Silverton_discharge.txt'
Animas_R_at_Silverton_discharge = create_dataframe_from_txt(Animas_R_at_Silverton_path, 'Animas_R_at_Silverton_discharge')
Animas_R_at_Silverton_discharge['Silverton_Discharge'] = pd.to_numeric(Animas_R_at_Silverton_discharge['19591_00060_00003'])
Animas_R_at_Silverton_discharge.drop(columns=['19591_00060_00003_cd', 'agency_cd', 'site_no', '19591_00060_00003'], inplace=True)
scaler = StandardScaler()
Animas_R_at_Silverton_discharge['Silverton_Discharge'] = scaler.fit_transform(Animas_R_at_Silverton_discharge)

Howard_a_Hanson_Reservoir_Near_Palmer_elevation_path = '/data/Hydra_Work/HydroBasin_Data/Howard_a_Hanson_Reservoir_Near_Palmer_elevation.txt'
Howard_a_Hanson_Reservoir_Near_Palmer_elevation = create_dataframe_from_txt(Howard_a_Hanson_Reservoir_Near_Palmer_elevation_path, 'Howard_a_Hanson_Reservoir_Near_Palmer_elevation')
Howard_a_Hanson_Reservoir_Near_Palmer_elevation['lake_elevation'] = pd.to_numeric(Howard_a_Hanson_Reservoir_Near_Palmer_elevation['148899_62614_30800'])
Howard_a_Hanson_Reservoir_Near_Palmer_elevation.drop(columns=['agency_cd', 'site_no', '148899_62614_30800_cd', '148899_62614_30800'], inplace=True)
scaler = StandardScaler()
Howard_a_Hanson_Reservoir_Near_Palmer_elevation['lake_elevation'] = scaler.fit_transform(Howard_a_Hanson_Reservoir_Near_Palmer_elevation)


Owyhee_r_nr_rome_discharge_path = '/data/Hydra_Work/HydroBasin_Data/Owyhee_r_nr_rome_discharge.txt'
Detroit_Upstream_path = '/data/Hydra_Work/HydroBasin_Data/Detroit_Upstream.txt'
Yampa_Upstream_path = '/data/Hydra_Work/HydroBasin_Data/Yamp_r_bl_craig.txt'

Owyhee_r_nr_rome_discharge = create_dataframe_from_txt(Owyhee_r_nr_rome_discharge_path, 'Owyhee_r_nr_rome_discharge')
Detroit_Upstream = create_dataframe_from_txt(Detroit_Upstream_path, 'Detroit_Upstream')
Yampa_Upstream = create_dataframe_from_txt(Yampa_Upstream_path, 'Yampa_Upstream')

Owyhee_r_nr_rome_discharge['Upstream_discharge'] = pd.to_numeric(Owyhee_r_nr_rome_discharge['113191_00060_00003'])
Owyhee_r_nr_rome_discharge.drop(columns=['agency_cd', 'site_no', '113191_00060_00003_cd', '113191_00060_00003'], inplace=True)

Detroit_Upstream['Upstream_discharge'] = pd.to_numeric(Detroit_Upstream['113880_00060_00003'])
Detroit_Upstream.drop(columns=['agency_cd', 'site_no', '113880_00060_00003_cd', '113880_00060_00003'], inplace=True)

Yampa_Upstream['Upstream_discharge'] = pd.to_numeric(Yampa_Upstream['325850_00060_00003'])
Yampa_Upstream.drop(columns=['agency_cd', 'site_no', '325850_00060_00003_cd', '325850_00060_00003'], inplace=True)

scaler = StandardScaler()
Owyhee_r_nr_rome_discharge['Upstream_discharge'] = scaler.fit_transform(Owyhee_r_nr_rome_discharge)
scaler = StandardScaler()
Detroit_Upstream['Upstream_discharge'] = scaler.fit_transform(Detroit_Upstream)
scaler = StandardScaler()
Yampa_Upstream['Upstream_discharge'] = scaler.fit_transform(Yampa_Upstream)

In [7]:
# For year in years, add entries from Animas_R_at_Silverton_discharge with the same dates to era5['animas_r_durango_year']
years = np.arange(2000,2024, 2)
# years = np.array([year for year in years if year not in [2002, 2012, 2014]])

extra_basins = ['owyhee_r_bl_owyhee_dam', 'yampa_r_nr_maybell', 'detroit_lake_inflow', 'animas_r_at_durango']
extra_data = [Owyhee_r_nr_rome_discharge, Yampa_Upstream, Detroit_Upstream, Animas_R_at_Silverton_discharge]
for (i,basin) in enumerate(extra_basins):
    for year in years:
        era5[f'{basin}_with_upstream_{year}'] = era5[f'{basin}_{year}'].join(
            extra_data[i], 
            on= 'date', 
            how='left', 
        )
        
        
extra_dict = {
    'owyhee_r_bl_owyhee_dam': Owyhee_r_nr_rome_discharge,
    'yampa_r_nr_maybell': Yampa_Upstream,
    'detroit_lake_inflow': Detroit_Upstream,
    'animas_r_at_durango': Animas_R_at_Silverton_discharge
}

In [8]:
era5['animas_r_at_durango_with_upstream_2000']

,precipitation,runoff,evaporation,temperature,snow depth water equivalent,soil water volume,day_of_year,day_of_year_cos,Silverton_Discharge
date,,,,,,,,,
1999-10-01,-0.434762,0.108835,-0.017115,0.509120,-0.61142,0.083416,-1.771206,-0.124569,-0.148486
1999-10-02,-0.433828,0.141387,-0.217766,0.567723,-0.61142,0.025434,-1.770868,-0.100968,-0.174537
1999-10-03,-0.433133,0.129390,-0.232486,0.608897,-0.61142,-0.031397,-1.770079,-0.077376,-0.194799
1999-10-04,-0.434553,0.117598,-0.236462,0.472473,-0.61142,-0.088387,-1.768840,-0.053800,-0.220850
1999-10-05,-0.434697,0.106178,-0.154005,0.633629,-0.61142,-0.139948,-1.767150,-0.030246,-0.235322
...,...,...,...,...,...,...,...,...,...
2000-07-27,-0.278002,-0.124987,-1.644632,1.276848,-0.61142,-0.103534,-0.920063,-1.361399,-0.356893
2000-07-28,-0.402423,-0.135212,-1.246671,1.448760,-0.61142,-0.234524,-0.943473,-1.350819,-0.380049
2000-07-29,-0.389912,-0.139055,-1.373138,1.539850,-0.61142,-0.411604,-0.966678,-1.339878,-0.397417
2000-07-30,-0.386088,-0.142650,-1.209186,1.381296,-0.61142,-0.512887,-0.989670,-1.328579,-0.403206
2000-07-31,-0.154680,-0.134850,-1.485980,1.237599,-0.61142,-0.491898,-1.012443,-1.316924,-0.408995

In [9]:
years = np.arange(2000,2024, 2)
for year in years:
    era5[f'animas_r_at_durango_with_upstream_{year}'] = era5[f'animas_r_at_durango_{year}'].join(
        Animas_R_at_Silverton_discharge, 
        on= 'date', 
        how='left', 
        rsuffix='_silverton'
    )

# Tuning individual basins

In [10]:
LR = 1e-3
static_size = np.shape(static_variables)[1]
forecast_size = np.shape(seasonal_forecasts['american_river_folsom_lake_2000_apr'])[1]
History_Fourier_in_forcings = 0 #2*3*(6 - 1)
Climate_guess = 0 #3 # THis is about climatology, not climate indices
History_Statistics_in_forcings = 0  #5*2

forecast_input_size = forecast_size + static_size + History_Fourier_in_forcings + History_Statistics_in_forcings  + Climate_guess + 3
output_size, head_hidden_size, head_num_layers =  3, 64, 3
hindcast_input_size = 22 # 22 with flow

In [11]:

def define_models(hindcast_input_size, forecast_input_size, hidden_size, num_layers, dropout, bidirectional, learning_rate, copies = 3, forecast_output_size = 3, device = device):
    models = {}
    params_to_optimize = {}
    optimizers = {}
    schedulers = {}
    
    hindcast_output_size = forecast_output_size
    for copy in range(copies):
        models[copy] = Google_Model_Block(hindcast_input_size, forecast_input_size, hindcast_output_size, forecast_output_size, hidden_size, num_layers, device, dropout, bidirectional)
        
        models[copy].to(device)
        params_to_optimize[copy] = list(models[copy].parameters())
        # Probably should be doing 1e-2 and 10
        optimizers[copy] = torch.optim.Adam(params_to_optimize[copy], lr= learning_rate, weight_decay = 1e-5)
        schedulers[copy] = lr_scheduler.StepLR(optimizers[copy], step_size= 5000, gamma=0.95) #.CosineAnnealingLR(optimizers[copy], T_max = 100000,)

        

    return models, params_to_optimize, optimizers, schedulers

In [28]:
import ray
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper
from ray.tune.search.optuna import OptunaSearch
import optuna

years = np.arange(2010,2024, 2).tolist()

# Fixed parameters
total_epochs = 30 # Will be higher in reality, this is just to make the plots
n_epochs = 1  # Epochs between tests
group_lengths = [1] #np.arange(180) 1 Day ahead for streamlined version
batch_size = 256
copies = 1

# parameters to tune
hidden_sizes = [64] # 64 converged upon
num_layers =  [1]
dropout = [0]
bidirectional = [False] #[True, False]
learning_rate = [5e-3] #[1e-3, 1e-5]
Upstream = [False]

extra_basins = ['green_r_bl_howard_a_hanson_dam']
# Set up configuration space
config_space = {

    "hidden_size": tune.grid_search(hidden_sizes),
    "num_layers": tune.grid_search(num_layers),
    "dropout": tune.grid_search(dropout),
    "bidirectional": tune.grid_search(bidirectional),
    "learning_rate": tune.grid_search(learning_rate),
    "basin":  tune.grid_search(extra_basins), #basins
    'test_year': tune.grid_search(years), #list(np.arange(2006,2024,2))
    'Use_Upstream': tune.grid_search(Upstream)

}

In [29]:
def train_model(config):

    All_Dates = ray.get(All_Dates_id)  

    years = np.arange(2000,2024, 2).tolist()
    test_year = config['test_year']
    val_years = [years[years.index(test_year)-1], years[years.index(test_year)-2]  ]
    train_years = [year for year in years if year not in [test_year] + val_years]
    
    Test_Dates = All_Dates[All_Dates.year == test_year]
    Val_Dates = All_Dates[All_Dates.year.isin(val_years)]
    Train_Dates = All_Dates[All_Dates.year.isin(train_years)]

    era5 = ray.get(era5_id)  
    daily_flow = ray.get(daily_flow_id)  
    climatological_flows = ray.get(climatological_flows_id)
    climate_indices = ray.get(climate_indices_id)
    seasonal_forecasts = ray.get(seasonal_forecasts_id)
    Static_variables = ray.get(Static_variables_id)
    
    basin = config["basin"]
        
    if config['Use_Upstream']:
        for year in years:
            era5[f'{basin}_{year}'] = era5[f'{basin}_with_upstream_{year}']  
    

    val_loss = 1000

    day = 1


    save_path = f'/data/Hydra_Work/{day}_Day_No_Forecast_Validation_Models/{test_year}/Specific_LSTM_Model/{basin}_specific.pth'
    loss_path = f'/data/Hydra_Work/{day}_Day_No_Forecast_Validation_Models/{test_year}/Specific_LSTM_Model/{basin}_specific_loss.txt'

    
    if not os.path.exists(loss_path):
        # If the file does not exist, create it and write val_loss to it
        with open(loss_path, 'w') as file:
            file.write('%f' % val_loss)
    
    copies = 1
    device = torch.device('cuda' if torch.cuda.
                    is_available() else 'cpu')

    
    hindcast_size = hindcast_input_size
    if config['Use_Upstream']:
        hindcast_size = hindcast_input_size + 1
        
    models, params_to_optimize, optimizers, schedulers = define_models(hindcast_size, forecast_input_size,
    config["hidden_size"], config["num_layers"], config["dropout"],
    config["bidirectional"], config["learning_rate"], copies=copies, device = device)

    losses, val_losses = [], []

    for epoch in range(total_epochs):

        train_losses = {}
        epoch_val_losses = {}

        for copy in range(copies):

             # Need to fix the outputs of No_Body_Model_Run
            train_losses[copy], Climate_Loss = No_Body_Model_Run(Train_Dates, [basin], models[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs=n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, specialised=True)
            epoch_val_losses[copy], Climate_Loss = No_Body_Model_Run(Val_Dates, [basin], models[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs=n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=False, device=device, specialised=True)

        loss = np.mean(list(train_losses.values())) - Climate_Loss
        

        candidate_val_loss = ((np.mean( list(epoch_val_losses.values()) ).mean() - Climate_Loss)[0])/np.mean(Climate_Loss)
        val_loss = np.min([val_loss, candidate_val_loss ])
        if candidate_val_loss == val_loss:
             torch.save(models[0], save_path)
             
        
        # Check best loss so far for this model
        with open(loss_path, 'r') as file:
            # Read the entire contents of the file
            Overall_Best_Val_Loss = float(file.read())

        if val_loss < Overall_Best_Val_Loss:
            torch.save(models[0], save_path)

            with open(loss_path, 'w') as f:
                f.write('%f' % val_loss)


        ray.train.report({'val_loss' : val_loss})
        #print(candidate_val_loss)
        losses.append(loss)
        val_losses.append(val_loss)


    return val_loss

In [30]:
from ray import train, tune


ray.shutdown()
ray.init(runtime_env = { "env_vars":   {"PYTHONPATH": '/data/Hydra_Work/Competition_Functions/' } } )
         
All_Dates_id = ray.put(All_Dates)   
era5_id = ray.put(era5)  
daily_flow_id = ray.put(daily_flow)  
climatological_flows_id = ray.put(climatological_flows)
climate_indices_id = ray.put(climate_indices)
seasonal_forecasts_id = ray.put(seasonal_forecasts)
Static_variables_id = ray.put(static_variables)

2024-08-23 14:02:47,353	INFO worker.py:1724 -- Started a local Ray instance.

In [31]:
asha_scheduler = ASHAScheduler(
    time_attr='training_iteration',
    metric='val_loss',
    mode='min',
    max_t=100,
    grace_period=30,
    reduction_factor=2,
    brackets=1,
)


plateau_stopper = TrialPlateauStopper(
    metric="val_loss",
    num_results = 30,
    grace_period=70,
    mode="min",
)

In [33]:
runs = 7
# At weekly:
# Animas has {'hidden_size': 128, 'num_layers': 3, 'dropout': 0.1, 'bidirectional': False, 'learning_rate': 1e-05}, 64,3,0.1. Results for 64, 1, 0.1, True identical
def objective(config):   

    device = torch.device('cuda' if torch.cuda.
                      is_available() else 'cpu')
    
    #print('Device available is', device)
    

    score = train_model(config) # Have training loop in here that outputs loss of model
    return {"val_loss": score}

#basin = 'stehekin_r_at_stehekin'

#, search_alg = optuna_search
optuna_tune_config = tune.TuneConfig(scheduler=asha_scheduler)
tune_config = tune.TuneConfig(scheduler=asha_scheduler)
running_tune_config = tune.TuneConfig()

run_config=train.RunConfig(stop= plateau_stopper)

# Note using < 1gb per run stops pylance from crashing I think
# Without Optun
tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 15/runs, "gpu": 1/(runs)}), param_space=config_space, tune_config = tune_config, run_config = run_config) 
# With Optuna
#tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 1, "gpu": 1/16}), param_space = optuna_config_space, tune_config = optuna_tune_config, run_config = run_config) 

results = tuner.fit()
best_config = results.get_best_result(metric="val_loss", mode="min").config
print(best_config)



# Define the file path where you want to save the best configuration
file_path = f"/data/Hydra_Work/Tuning/Config_Text/{basin}_best_config.txt"
# Open the file in write mode and save the configuration
with open(file_path, "w") as f:
    f.write(str(best_config))

print("Best configuration saved to:", file_path)

2024-08-23 14:35:23,740	INFO tune.py:1042 -- Total run time: 1942.20 seconds (1942.17 seconds for the tuning loop).

{'hidden_size': 64, 'num_layers': 1, 'dropout': 0, 'bidirectional': False, 'learning_rate': 0.005, 'basin': 'green_r_bl_howard_a_hanson_dam', 'test_year': 2020, 'Use_Upstream': False}
Best configuration saved to: /data/Hydra_Work/Tuning/Config_Text/animas_r_at_durango_best_config.txt

In [57]:
results_df = results.get_dataframe()
results_df[results_df['val_loss'] < -0.1][['val_loss', 'config/Use_Upstream', 'config/test_year']]

    val_loss  config/Use_Upstream  config/test_year
0  -0.794160                 True              2000
1  -0.797231                False              2000
2  -0.681744                 True              2002
3  -0.686602                False              2002
4  -0.623500                 True              2004
5  -0.618707                False              2004
6  -0.762844                 True              2006
7  -0.753896                False              2006
8  -0.788199                 True              2008
9  -0.798254                False              2008
10 -0.758955                 True              2010
11 -0.754143                False              2010
12 -0.714125                 True              2012
13 -0.701066                False              2012
14 -0.683948                 True              2014
15 -0.673752                False              2014
16 -0.723872                 True              2016
17 -0.733273                False              2016
18 -0.816858                 True              2018
19 -0.816385                False              2018
20 -0.867515                 True              2020
21 -0.870321                False              2020
22 -0.860336                 True              2022
23 -0.858861                False              2022

In [ ]:
Safe_Basins = list(results_df[results_df['val_loss'] < -0.05]['config/basin'].values)
Retrain_Basins = list(set(basins) - set(Safe_Basins))
Retrain_Basins

In [67]:
from scipy import stats

results_df = results.get_dataframe()
columns_to_drop = ['timestamp', 'checkpoint_dir_name', 'done', 'training_iteration', 
                   'trial_id', 'date', 'time_this_iter_s', 'time_total_s', 'pid', 
                   'hostname', 'node_ip', 'time_since_restore', 'iterations_since_restore']

# Drop the columns
results_df.drop(columns=columns_to_drop, inplace=True)

val_loss_bidirectional_true = results_df[results_df['config/Use_Upstream'] == True]['val_loss']
val_loss_bidirectional_false = results_df[results_df['config/Use_Upstream'] == False]['val_loss']

# Perform a t-test
t_statistic, p_value = stats.ttest_ind(val_loss_bidirectional_false, val_loss_bidirectional_true)

# Print the results
print("T-Statistic:", t_statistic)
print("P-Value:", p_value)

# Check if the difference in means is statistically significant
alpha = 0.05  # Significance level
if p_value < alpha:
    print("The difference in mean val_loss is statistically significant.")
else:
    print("The difference in mean val_loss is not statistically significant.")

T-Statistic: -0.06405502524392012
P-Value: 0.949504879012239
The difference in mean val_loss is not statistically significant.

In [ ]:
# Loading models
Tuned_Models = {}
for basin in basins:
    Tuned_Models[basin] = torch.load(f'/data/Hydra_Work/Post_Rodeo_Work/Tuned_Single_Models/basin.pth')

# Tuning General Model

In [9]:
LR = 1e-3
static_size = np.shape(static_variables)[1]
forecast_size = np.shape(seasonal_forecasts['american_river_folsom_lake_2000_apr'])[1]
History_Fourier_in_forcings = 0 #2*3*(6 - 1)
Climate_guess = 0 #3
History_Statistics_in_forcings = 0 #5*2

forecast_input_size = forecast_size + static_size + History_Fourier_in_forcings + History_Statistics_in_forcings  + Climate_guess + 3
output_size, head_hidden_size, head_num_layers =  3, 64, 3
hindcast_input_size = 22 #

In [10]:
import ray
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper

# Fixed parameters
total_epochs = 200
n_epochs = 1 # Epochs between tests
group_lengths = [1] # 
batch_size = 64
copies = 1

# parameters to tune
# I tuned to 128,2,0.4,False,1e-3 
hidden_sizes = [64]
num_layers = [2]
dropout = [0.2] # 0.2 0.4 both equal
bidirectional =  [False]
learning_rate = [1e-3]
batch_size = [128] 

config_space = {
    "hidden_size": tune.grid_search(hidden_sizes),
    "num_layers": tune.grid_search(num_layers),
    "dropout": tune.grid_search(dropout),
    "bidirectional": tune.grid_search(bidirectional),
    "learning_rate": tune.grid_search(learning_rate),
    "batch_size": tune.grid_search(batch_size),
    'test_year': tune.grid_search(list(np.arange(2000,2022,2)) )
    
}


# Places to save info
model_dir = '/data/Hydra_Work/Post_Rodeo_Work/Tuned_General_Model/'

In [11]:
def train_model_general(config):
    
    All_Dates = ray.get(All_Dates_id)  
    
    years = list(np.arange(2000,2024,2))
    test_year = config['test_year']
    val_years = [years[years.index(test_year)-1], years[years.index(test_year)-2]  ]
    train_years = [year for year in years if year not in [test_year] + val_years]
    
    Test_Dates = All_Dates[All_Dates.year == test_year]
    Val_Dates = All_Dates[All_Dates.year.isin(val_years)]
    Train_Dates = All_Dates[All_Dates.year.isin(train_years)]
    
    era5 = ray.get(era5_id)  
    daily_flow = ray.get(daily_flow_id)  
    climatological_flows = ray.get(climatological_flows_id)
    climate_indices = ray.get(climate_indices_id)
    seasonal_forecasts = ray.get(seasonal_forecasts_id)
    Static_variables = ray.get(Static_variables_id)

    copies = 1
    
    device = torch.device('cuda' if torch.cuda.
                    is_available() else 'cpu')

    day = 1
    save_path = f'/data/Hydra_Work/{day}_Day_No_Forecast_Validation_Models/{test_year}/General_LSTM_Model/General_LSTM.pth'
    loss_path = f'/data/Hydra_Work/{day}_Day_No_Forecast_Validation_Models/{test_year}/General_LSTM_Model/General_LSTM_loss.txt'

    val_loss = 1000
    
    
    if not os.path.exists(loss_path):
        # If the file does not exist, create it and write val_loss to it
        with open(loss_path, 'w') as file:
            file.write('%f' % val_loss)
    
  
    models, params_to_optimize, optimizers, schedulers = define_models(hindcast_input_size, forecast_input_size,
    config["hidden_size"], config["num_layers"], config["dropout"],
    config["bidirectional"], config["learning_rate"], copies=copies, device = device)

    batch_size = config["batch_size"]
    losses, val_losses = [], []

    for epoch in range(total_epochs):

        train_losses = {}
        epoch_val_losses = {}

        for copy in range(copies):

             # Need to fix the outputs of No_Body_Model_Run
            train_losses[copy], Climate_Loss = No_Body_Model_Run(Train_Dates, basins, models[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs=n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, specialised=False)
            epoch_val_losses[copy], Climate_Loss = No_Body_Model_Run(Val_Dates, basins, models[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs=n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=False, device=device, specialised=False)

        loss = np.mean(list(train_losses.values())) - Climate_Loss


        candidate_val_loss = ((np.mean(list(epoch_val_losses.values())).mean() - Climate_Loss)[0])/np.mean(Climate_Loss)
        val_loss = np.min([val_loss, candidate_val_loss ])
        
        # Check best loss so far for this model
        with open(loss_path, 'r') as file:
            # Read the entire contents of the file
            Overall_Best_Val_Loss = float(file.read())

        if val_loss < Overall_Best_Val_Loss:
            torch.save(models[0], save_path)

            with open(loss_path, 'w') as f:
                f.write('%f' % val_loss)

            
               
        ray.train.report({'val_loss' : val_loss})

        losses.append(loss)
        val_losses.append(candidate_val_loss)
        #print(val_losses)
        #print(candidate_val_loss)
        #print(loss/np.mean(Climate_Loss))
    return val_loss

In [12]:
from ray import train, tune
import ray
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper
from ray.tune.search.optuna import OptunaSearch
import optuna


ray.shutdown()
ray.init(runtime_env = { "env_vars":   {"PYTHONPATH": '/data/Hydra_Work/Competition_Functions/' } } )
         
All_Dates_id = ray.put(All_Dates)  
era5_id = ray.put(era5)  
daily_flow_id = ray.put(daily_flow)  
climatological_flows_id = ray.put(climatological_flows)
climate_indices_id = ray.put(climate_indices)
seasonal_forecasts_id = ray.put(seasonal_forecasts)
Static_variables_id = ray.put(static_variables)

2024-08-02 15:07:32,922	INFO worker.py:1724 -- Started a local Ray instance.

In [ ]:
# asha_scheduler = ASHAScheduler(
#     time_attr='training_iteration',
#     metric='val_loss',
#     mode='min',
#     max_t=100,
#     grace_period=20,
#     reduction_factor=2,
#     brackets=1,
# )


plateau_stopper = TrialPlateauStopper(
    metric="val_loss",
    num_results = 20,
    grace_period=100,
    mode="min",
)

In [ ]:
# {'hidden_size': 256, 'num_layers': 3, 'dropout': 0.1, 'bidirectional': True, 'learning_rate': 0.001}
# 7 Days:  128	2	0.4	False	0.001
def objective(config):  
    device = torch.device('cuda' if torch.cuda.
                      is_available() else 'cpu')
    
    #print('Device available is', device)
    

    score = train_model_general(config) # Have training loop in here that outputs loss of model
    return {"val_loss": score}


#, search_alg = optuna_search
# optuna_tune_config = tune.TuneConfig(scheduler=asha_scheduler)
# tune_config = tune.TuneConfig(scheduler=asha_scheduler)
run_config=train.RunConfig(stop= plateau_stopper)

runs = 12
# Without Optuna
tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 15/runs , "gpu": 1/runs }), param_space=config_space, run_config = run_config) 
# With Optuna
#tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 1, "gpu": 1/16}), param_space = optuna_config_space, tune_config = optuna_tune_config, run_config = run_config) 

results = tuner.fit()
# try get_best_checkpoint, or change val to be maximum of current val_loss and previous ones
best_config = results.get_best_result(metric="val_loss", mode="min").config
print(best_config)
file_path = f"/data/Hydra_Work/Tuning/Config_Text/General_Model_best_config.txt"

# Open the file in write mode and save the configuration
with open(file_path, "w") as f:
    f.write(str(best_config))

print("Best configuration saved to:", file_path)

2024-07-09 12:42:48,920	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', 'd0c36a7a')}
2024-07-09 12:48:23,306	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '77ade844')}
2024-07-09 12:49:12,698	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '1f98018a')}
2024-07-09 12:50:12,090	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '80f16ada')}
2024-07-09 12:50:34,631	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '56d80434')}
2024-07-09 12:51:29,518	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '5a92826b')}
2024-07-09 12:53:53,715	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '6269ca81')}
2024-07-09 12:55:59,763	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', 'd31ea24e')}
2024-07-09 12:56:02,386	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '34b3c1e4')}
2024-07-09 12:57:12,549	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '52467d93')}
2024-07-09 12:57:33,134	INFO tensorboardx.py:275 -- Removed the following hyperparameter values when logging to tensorboard: {'test_year': ('__ref_ph', '93632d75')}
2024-07-09 12:57:33,216	INFO tune.py:1042 -- Total run time: 6594.15 seconds (6594.01 seconds for the tuning loop).

{'hidden_size': 64, 'num_layers': 2, 'dropout': 0.2, 'bidirectional': False, 'learning_rate': 0.001, 'batch_size': 128, 'test_year': 2000}
Best configuration saved to: /data/Hydra_Work/Tuning/Config_Text/General_Model_best_config.txt

In [ ]:
results_df = results.get_dataframe()
results_df[results_df['val_loss'] < -0.15]

,val_loss,timestamp,checkpoint_dir_name,done,training_iteration,trial_id,date,time_this_iter_s,time_total_s,pid,...,time_since_restore,iterations_since_restore,config/hidden_size,config/num_layers,config/dropout,config/bidirectional,config/learning_rate,config/batch_size,config/test_year,logdir
0,-0.916139,1720529832,None,True,103,745ff_00000,2024-07-09_12-57-12,15.956244,6565.274128,66433,...,6565.274128,103,64,2,0.2,False,0.001,128,2000,745ff_00000
1,-0.908900,1720529633,None,True,100,745ff_00001,2024-07-09_12-53-53,21.221126,6365.614576,66437,...,6365.614576,100,64,2,0.2,False,0.001,128,2002,745ff_00001
2,-0.898753,1720529759,None,True,100,745ff_00002,2024-07-09_12-55-59,17.372711,6491.740392,66461,...,6491.740392,100,64,2,0.2,False,0.001,128,2004,745ff_00002
3,-0.897664,1720529303,None,True,100,745ff_00003,2024-07-09_12-48-23,33.321624,6036.288099,66471,...,6036.288099,100,64,2,0.2,False,0.001,128,2006,745ff_00003
4,-0.895664,1720529489,None,True,100,745ff_00004,2024-07-09_12-51-29,18.703527,6222.730413,66473,...,6222.730413,100,64,2,0.2,False,0.001,128,2008,745ff_00004
5,-0.892598,1720529412,None,True,100,745ff_00005,2024-07-09_12-50-12,34.377634,6144.760104,66487,...,6144.760104,100,64,2,0.2,False,0.001,128,2010,745ff_00005
6,-0.898200,1720529762,None,True,100,745ff_00006,2024-07-09_12-56-02,18.797728,6494.589055,66488,...,6494.589055,100,64,2,0.2,False,0.001,128,2012,745ff_00006
7,-0.892137,1720529434,None,True,100,745ff_00007,2024-07-09_12-50-34,38.484445,6165.806365,66489,...,6165.806365,100,64,2,0.2,False,0.001,128,2014,745ff_00007
8,-0.899643,1720529352,None,True,100,745ff_00008,2024-07-09_12-49-12,40.663137,6086.855739,66502,...,6086.855739,100,64,2,0.2,False,0.001,128,2016,745ff_00008
9,-0.906679,1720529853,None,True,100,745ff_00009,2024-07-09_12-57-33,16.388896,6585.348883,66507,...,6585.348883,100,64,2,0.2,False,0.001,128,2018,745ff_00009
10,-0.905118,1720528968,None,True,100,745ff_00010,2024-07-09_12-42-48,28.114495,5702.012003,66512,...,5702.012003,100,64,2,0.2,False,0.001,128,2020,745ff_00010

In [ ]:
General_Model = torch.load('/data/Hydra_Work/Post_Rodeo_Work/Tuned_General_Model/General_model.pth')

FileNotFoundError: [Errno 2] No such file or directory: '/data/Hydra_Work/Post_Rodeo_Work/Tuned_General_Model/General_model.pth'

# Tuning Hydra Model

In [70]:
def define_models_hydra(body_hindcast_input_size, body_forecast_input_size, body_output_size, body_hidden_size, body_num_layers, body_dropout,
                        head_hidden_size, head_num_layers, head_forecast_output_size, head_dropout, bidirectional, basins,
                        learning_rate_general_head, learning_rate_head, learning_rate_body, LR = 1e-3, 
                        additional_specific_head_hindcast_input_size = 1, additional_specific_head_forecast_input_size = 0,
                        copies=1, device=None):
    Hydra_Bodys = {}
    Basin_Heads = {}
    General_Heads = {}   
    general_optimizers = {}
    specific_optimizers = {}
    specific_schedulers = {}
    general_schedulers = {}
    optimizers = {}
    schedulers = {}
    
    body_forecast_output_size = body_output_size
    body_hindcast_output_size = body_output_size
    
    # Define head hindcast size as head-forecast for simplicty
    head_hindcast_output_size = head_forecast_output_size
    specific_head_hindcast_output_size = head_forecast_output_size
    specific_head_forecast_output_size = head_forecast_output_size
    specific_head_hidden_size = head_hidden_size
    specific_head_num_layers = head_num_layers
    
    # Head takes Body as inputs
    #head_hindcast_input_size = body_hindcast_input_size 
    head_hindcast_input_size = body_hindcast_output_size
    head_forecast_input_size = body_forecast_output_size
    
    # Specific input size
    specific_head_hindcast_input_size = head_hindcast_input_size + additional_specific_head_hindcast_input_size
    specific_head_forecast_input_size = head_forecast_input_size + additional_specific_head_forecast_input_size
    
    for copy in range(copies):
        Hydra_Bodys[copy] = Google_Model_Block(body_hindcast_input_size, body_forecast_input_size, body_hindcast_output_size, body_forecast_output_size, body_hidden_size, body_num_layers, device, body_dropout, bidirectional)
        General_Heads[copy] = Google_Model_Block(head_hindcast_input_size, head_forecast_input_size, head_hindcast_output_size, head_forecast_output_size, head_hidden_size, head_num_layers, device, head_dropout, bidirectional)
        Basin_Heads[copy] = Specific_Heads(basins, specific_head_hindcast_input_size, specific_head_forecast_input_size, specific_head_hindcast_output_size, specific_head_forecast_output_size, specific_head_hidden_size, specific_head_num_layers, device, head_dropout, bidirectional)


        specific_head_parameters = list()
        for basin, model in Basin_Heads[copy].items():
            specific_head_parameters += list(model.parameters())

        optimizers[copy] = torch.optim.Adam(
        # Extra LR is the global learning rate, not really important
        [
            {"params": General_Heads[copy].parameters(), "lr": learning_rate_general_head},
            #{"params": specific_head_parameters, "lr": 0*learning_rate_head},
            {"params": Hydra_Bodys[copy].parameters(), "lr": learning_rate_body},
        ],
        lr=0, weight_decay = 1e-5) #1e-4 good so far, 3 not so food

        general_optimizers[copy] = torch.optim.Adam(
        # Extra LR is the global learning rate, not really important
        [
            {"params": General_Heads[copy].parameters(), "lr": learning_rate_general_head},
            {"params": Hydra_Bodys[copy].parameters(), "lr": learning_rate_body},
        ],
        lr=LR, )
        
        specific_optimizers[copy] = torch.optim.Adam(
        [
        {"params": specific_head_parameters, "lr": learning_rate_head}        
        ]
        )
        
        schedulers[copy] = lr_scheduler.StepLR(optimizers[copy], 1, gamma=0.95) #.CosineAnnealingLR(optimizers[copy], T_max= 100000, eta_min= 1e-4,)
        general_schedulers[copy] = lr_scheduler.StepLR(general_optimizers[copy], 1, gamma=1)
        specific_schedulers[copy] = lr_scheduler.StepLR(specific_optimizers[copy], 1, gamma=1)       
    return Hydra_Bodys, General_Heads, Basin_Heads, optimizers, schedulers, general_optimizers, general_schedulers, specific_optimizers, specific_schedulers

In [71]:
LR = 1e-3
static_size = np.shape(static_variables)[1]
forecast_size = np.shape(seasonal_forecasts['american_river_folsom_lake_2000_apr'])[1]
History_Fourier_in_forcings = 0 #2*3*(6 - 1)
Climate_guess = 0 #3
History_Statistics_in_forcings = 0 # 5*2

forecast_input_size = forecast_size + static_size + History_Fourier_in_forcings + History_Statistics_in_forcings  + Climate_guess + 3
output_size, head_hidden_size, head_num_layers =  3, 64, 3
body_hindcast_input_size = 21
body_forecast_input_size = forecast_input_size


Overall_Best_Val_Loss = 999

In [90]:
import ray
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper

# Fixed parameters
total_epochs = 200
n_epochs = 1 # Epochs between tests
group_lengths = [1] #np.arange(180)

copies = 1
head_output_size = 3

body_hidden_sizes =  [64]
body_num_layers = [1]
body_dropouts = [0] 
body_learning_rates = [1e-3] 
body_outputs = [16] # retest this at some point

head_hidden_sizes = [32]
head_num_layers = [1]
head_dropouts = [0.0]
head_learning_rates = [1e-3] #1e-2
batch_size = [128]
LR = 1e-3
bidirectionals = [False]
spec_multiplier = [1]

Upstream = [True]
extra_basins = ['owyhee_r_bl_owyhee_dam', 'yampa_r_nr_maybell', 'detroit_lake_inflow', 'animas_r_at_durango']

warmup = [0]

config_space = {
    "body_hidden_size": tune.grid_search(body_hidden_sizes),
    "body_num_layer": tune.grid_search(body_num_layers),
    "body_dropout": tune.grid_search(body_dropouts),
    "bidirectional": tune.grid_search(bidirectionals),
    "body_output": tune.grid_search(body_outputs),
    "body_learning_rate": tune.grid_search(body_learning_rates),
    "head_hidden_size": tune.grid_search(head_hidden_sizes),
    "head_num_layer": tune.grid_search(head_num_layers),
    "head_dropout": tune.grid_search(head_dropouts),
    "head_learning_rate": tune.grid_search(head_learning_rates),
    "spec_multiplier": tune.grid_search(spec_multiplier),
    'batch_size': tune.grid_search(batch_size),
    'test_year': tune.grid_search(list(np.arange(2016,2024,2))), #
    'warmup': tune.grid_search(warmup),
    'Use_Upstream': tune.grid_search(Upstream),
    'basins': tune.grid_search(extra_basins)
}

# Places to save info
model_dir = '/data/Hydra_Work/Post_Rodeo_Work/Tuned_Hydra_Model/'

In [91]:
def train_model_hydra(config):

    All_Dates = ray.get(All_Dates_id)  
    
    
    years = list(np.arange(2000,2024,2))
    test_year = config['test_year']
    val_years = [years[years.index(test_year)-1], years[years.index(test_year)-2]  ]
    train_years = [year for year in years if year not in [test_year] + val_years]
    
    Test_Dates = All_Dates[All_Dates.year == test_year]
    Val_Dates = All_Dates[All_Dates.year.isin(val_years)]
    Train_Dates = All_Dates[All_Dates.year.isin(train_years)]

    Day = 1
    era5 = ray.get(era5_id)  
    daily_flow = ray.get(daily_flow_id)  
    climatological_flows = ray.get(climatological_flows_id)
    climate_indices = ray.get(climate_indices_id)
    seasonal_forecasts = ray.get(seasonal_forecasts_id)
    Static_variables = ray.get(Static_variables_id)  
    extra_dict = ray.get(extra_dict_id)
    
                        
    body_save_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/General_Head_Model/Hydra_Body_LSTM.pth'
    head_save_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/General_Head_Model/Hydra_Head_LSTM.pth'
    basin_heads_save_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/Basin_Head_Model'
                              
    loss_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/General_Head_Model/Hydra_LSTM_loss.txt'

    val_loss = 1000
    
    
    if not os.path.exists(loss_path):
        # If the file does not exist, create it and write val_loss to it
        with open(loss_path, 'w') as file:
            file.write('%f' % val_loss)


    copies = 1
    warmup = config['warmup']
    
    basin = config['basins']
    basins = [basin]
 
 
    additional_data = None
    if config['Use_Upstream']:
      additional_data = extra_dict[basin]
            
            
    additional_specific_head_hindcast_input_size = 1
    if config['Use_Upstream']:
        additional_specific_head_hindcast_input_size = 2
             

    
    best_val_loss = 100
    device = torch.device('cuda' if torch.cuda.
                    is_available() else 'cpu')
   

    general_head_learning_rate = config['body_learning_rate']
    Hydra_Bodys, General_Hydra_Heads, model_heads, optimizers, schedulers, general_optimizers, general_schedulers, specific_optimizers, specific_schedulers  = define_models_hydra(body_hindcast_input_size, body_forecast_input_size, config['body_output'],
                                config['body_hidden_size'], config['body_num_layer'], config['body_dropout'], 
                                config['head_hidden_size'], config['head_num_layer'], 3, config['head_dropout'], config['bidirectional'], basins,
                                general_head_learning_rate, config['head_learning_rate'], config['body_learning_rate'], LR, additional_specific_head_hindcast_input_size = additional_specific_head_hindcast_input_size, device = device
                                )
    
    Hydra_Bodys = {}
    for copy in range(copies):
        Hydra_Bodys[copy] = torch.load(body_save_path) 

    batch_size = config['batch_size']
                                                
    general_losses, specific_losses, general_val_losses, specific_val_losses, val_losses = [], [], [], [], []

    # Initialise, with dummy scheduler
    for copy in range(copies):
        # Initialise
        dummy_scheduler = lr_scheduler.StepLR(general_optimizers[copy],step_size = warmup, gamma = 0.8)

        Model_Run(Train_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
            Static_variables, additional_data, general_optimizers[copy], general_schedulers, criterion, early_stopper= None, n_epochs= warmup,
            batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, feed_forcing = False)

    # Would be great if I could initialise the specific heads with the general heads, or finetune the specific heads at the end
            
    for epoch in range(total_epochs):
        train_general_losses = {}
        train_specific_losses = {}
        train_climate_losses = {}
        epoch_val_general_losses = {}
        epoch_val_specific_losses = {}
        climate_losses = {}
        
        for copy in range(copies):
                        

            # Training General Head and Body
            # train_general_losses[copy], train_specific_losses[copy], train_climate_losses[copy] = Model_Run(Train_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
            #     Static_variables, additional_data, general_optimizers[copy], general_schedulers[copy], criterion, early_stopper= None, n_epochs= n_epochs,
            #     batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, feed_forcing = False)

            # Just tuning specific heads
            train_general_losses[copy], train_specific_losses[copy], train_climate_losses[copy] = Model_Run(Train_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, additional_data, specific_optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs= n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, feed_forcing = False)

            epoch_val_general_losses[copy], epoch_val_specific_losses[copy], climate_losses[copy] = Model_Run(Val_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, additional_data, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs= n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=False, device=device, feed_forcing = False)


        general_loss = np.mean(list(train_general_losses.values()))
        specific_loss = np.mean(list(train_specific_losses.values()))
        train_climate_loss = np.mean(list(train_climate_losses.values()))
        climate_loss = np.mean(list(climate_losses.values()))
        
        epoch_val_general_loss = np.mean(list(epoch_val_general_losses.values())).mean()
        epoch_val_specific_loss = np.mean(list(epoch_val_specific_losses.values())).mean()
        
        
        general_losses.append(general_loss)
        specific_losses.append(specific_loss)
        specific_val_losses.append(epoch_val_specific_loss)
        general_val_losses.append(epoch_val_general_loss)

        # val_loss = 0.5*(epoch_val_general_loss + epoch_val_specific_loss)
        
        val_loss = epoch_val_specific_loss
        candidate_val_loss = ((val_loss.mean() - climate_loss))/np.mean(climate_loss)
        best_val_loss = np.min([best_val_loss, candidate_val_loss ])
         
        with open(loss_path, 'r') as file:
            # Read the entire contents of the file
            Overall_Best_Val_Loss = float(file.read())

        # if best_val_loss < Overall_Best_Val_Loss:
        #     with open(loss_path, 'w') as f:
        #         f.write('%f' % best_val_loss)

        #     torch.save(Hydra_Bodys[0], body_save_path)
        #     torch.save(General_Hydra_Heads[0], head_save_path)
            # for basin in basins:
            #     torch.save(model_heads[0][basin], f"{basin_heads_save_path}/{basin}.path")
                
            
               
        ray.train.report({'val_loss' : best_val_loss})
        #print('Validation Loss', val_losses)
        #print('Training Loss', general_losses/train_climate_loss )
        #print(candidate_val_loss)
        val_losses.append(candidate_val_loss)

    return best_val_loss

In [92]:
import ray
from ray import train, tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper


ray.shutdown()
ray.init(runtime_env = { "env_vars":   {"PYTHONPATH": '/data/Hydra_Work/Competition_Functions/' } })
         
All_Dates_id = ray.put(All_Dates)  
era5_id = ray.put(era5)  
daily_flow_id = ray.put(daily_flow)  
climatological_flows_id = ray.put(climatological_flows)
climate_indices_id = ray.put(climate_indices)
seasonal_forecasts_id = ray.put(seasonal_forecasts)
Static_variables_id = ray.put(static_variables)
extra_dict_id = ray.put(extra_dict)

2024-08-02 16:59:34,320	INFO worker.py:1724 -- Started a local Ray instance.

In [93]:
asha_scheduler = ASHAScheduler(
    time_attr='training_iteration',
    metric='val_loss',
    mode='min',
    max_t=100,
    grace_period=20,
    reduction_factor=3,
    brackets=1,
)


plateau_stopper = TrialPlateauStopper(
    metric="val_loss",
    num_results = 100,
    grace_period=20,
    mode="min",
)

In [94]:
runs_per_iteration = 1
def objective(config):  
    device = torch.device('cuda' if torch.cuda.
                      is_available() else 'cpu')
    

    score = train_model_hydra(config) # Have training loop in here that outputs loss of model
    return {"val_loss": score}


run_config=train.RunConfig(stop= plateau_stopper)
# Can use fractions of GPU
tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 15/runs_per_iteration, "gpu": 1/(runs_per_iteration)}), param_space=config_space, run_config = run_config) 
    
results = tuner.fit()
best_config = results.get_best_result(metric="val_loss", mode="min").config
print(best_config)
file_path = f"/data/Hydra_Work/Tuning/Config_Text/Hydral_Model_best_config.txt"

# Open the file in write mode and save the configuration
with open(file_path, "w") as f:
    f.write(str(best_config))

print("Best configuration saved to:", file_path)

(objective pid=520228) works before prepare basins
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history
(objective pid=520228) works before calculate flow data
(objective pid=520228) works until making torch tensor
(objective pid=520228) works before process history

2024-08-02 16:59:54,051	ERROR tune_controller.py:1374 -- Trial task failed for trial objective_9e4a5_00000
Traceback (most recent call last):
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::ImplicitFunc.train() (pid=520228, ip=136.156.133.98, actor_id=345aab3416c3ab4ac3663bf401000000, repr=objective)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/air/_internal/util.py", line 88, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 115, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 332, in _trainable_func
    output = fn()
             ^^^^
  File "/home/gbmc/miniforge3/envs/Hydra_Code/lib/python3.11/site-packages/ray/tune/trainable/util.py", line 138, in inner
    return trainable(config, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_502246/3558679099.py", line 7, in objective
  File "/tmp/ipykernel_502246/3650301556.py", line 106, in train_model_hydra
  File "/data/Hydra_Work/Competition_Functions/Full_LSTM_ML_Functions.py", line 509, in Model_Run
    additional_list_torch = torch.stack(additional_data_torch_list, dim=0)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [1, 1] at entry 0 and [0, 1] at entry 1
2024-08-02 16:59:56,673	WARNING tune.py:186 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip.
2024-08-02 16:59:57,359	ERROR tune.py:1038 -- Trials did not complete: [objective_9e4a5_00000]
2024-08-02 16:59:57,360	INFO tune.py:1042 -- Total run time: 12.39 seconds (11.68 seconds for the tuning loop).
2024-08-02 16:59:57,361	WARNING tune.py:1057 -- Experiment has been interrupted, but the most recent state was saved.
Resume experiment with: Tuner.restore(path="/home/gbmc/ray_results/objective_2024-08-02_16-59-44", trainable=...)
2024-08-02 16:59:57,366	WARNING experiment_analysis.py:193 -- Failed to fetch metrics for 15 trial(s):
- objective_9e4a5_00001: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00001: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00001_1_Use_Upstream=True,basins=yampa_r_nr_maybell,batch_size=128,bidirectional=False,body_dropout=0,body_hidden__2024-08-02_16-59-45')
- objective_9e4a5_00002: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00002: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00002_2_Use_Upstream=True,basins=detroit_lake_inflow,batch_size=128,bidirectional=False,body_dropout=0,body_hidden_2024-08-02_16-59-45')
- objective_9e4a5_00003: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00003: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00003_3_Use_Upstream=True,basins=animas_r_at_durango,batch_size=128,bidirectional=False,body_dropout=0,body_hidden_2024-08-02_16-59-45')
- objective_9e4a5_00004: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00004: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00004_4_Use_Upstream=True,basins=owyhee_r_bl_owyhee_dam,batch_size=128,bidirectional=False,body_dropout=0,body_hid_2024-08-02_16-59-45')
- objective_9e4a5_00005: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00005: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00005_5_Use_Upstream=True,basins=yampa_r_nr_maybell,batch_size=128,bidirectional=False,body_dropout=0,body_hidden__2024-08-02_16-59-45')
- objective_9e4a5_00006: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00006: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00006_6_Use_Upstream=True,basins=detroit_lake_inflow,batch_size=128,bidirectional=False,body_dropout=0,body_hidden_2024-08-02_16-59-45')
- objective_9e4a5_00007: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00007: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00007_7_Use_Upstream=True,basins=animas_r_at_durango,batch_size=128,bidirectional=False,body_dropout=0,body_hidden_2024-08-02_16-59-45')
- objective_9e4a5_00008: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00008: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00008_8_Use_Upstream=True,basins=owyhee_r_bl_owyhee_dam,batch_size=128,bidirectional=False,body_dropout=0,body_hid_2024-08-02_16-59-45')
- objective_9e4a5_00009: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00009: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00009_9_Use_Upstream=True,basins=yampa_r_nr_maybell,batch_size=128,bidirectional=False,body_dropout=0,body_hidden__2024-08-02_16-59-45')
- objective_9e4a5_00010: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00010: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00010_10_Use_Upstream=True,basins=detroit_lake_inflow,batch_size=128,bidirectional=False,body_dropout=0,body_hidde_2024-08-02_16-59-45')
- objective_9e4a5_00011: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00011: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00011_11_Use_Upstream=True,basins=animas_r_at_durango,batch_size=128,bidirectional=False,body_dropout=0,body_hidde_2024-08-02_16-59-45')
- objective_9e4a5_00012: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00012: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00012_12_Use_Upstream=True,basins=owyhee_r_bl_owyhee_dam,batch_size=128,bidirectional=False,body_dropout=0,body_hi_2024-08-02_16-59-45')
- objective_9e4a5_00013: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00013: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00013_13_Use_Upstream=True,basins=yampa_r_nr_maybell,batch_size=128,bidirectional=False,body_dropout=0,body_hidden_2024-08-02_16-59-45')
- objective_9e4a5_00014: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00014: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00014_14_Use_Upstream=True,basins=detroit_lake_inflow,batch_size=128,bidirectional=False,body_dropout=0,body_hidde_2024-08-02_16-59-45')
- objective_9e4a5_00015: FileNotFoundError('Could not fetch metrics for objective_9e4a5_00015: both result.json and progress.csv were not found at /home/gbmc/ray_results/objective_2024-08-02_16-59-44/objective_9e4a5_00015_15_Use_Upstream=True,basins=animas_r_at_durango,batch_size=128,bidirectional=False,body_dropout=0,body_hidde_2024-08-02_16-59-45')
2024-08-02 16:59:57,367	WARNING experiment_analysis.py:584 -- Could not find best trial. Did you pass the correct `metric` parameter?

RuntimeError: No best trial found for the given metric: val_loss. This means that no trial has reported this metric, or all values reported for this metric are NaN. To not ignore NaN values, you can set the `filter_nan_and_inf` arg to False.

In [16]:
Animas_R_at_Silverton_discharge is not None

True

In [27]:
years = list(np.arange(2000,2024,2))
test_year = 2000
val_years = [years[years.index(test_year)-1], years[years.index(test_year)-2]  ]
train_years = [year for year in years if year not in [test_year] + val_years]

Test_Dates = All_Dates[All_Dates.year == test_year]
Val_Dates = All_Dates[All_Dates.year.isin(val_years)]
Train_Dates = All_Dates[All_Dates.year.isin(train_years)]

Day = 1
# era5 = ray.get(era5_id)  
# daily_flow = ray.get(daily_flow_id)  
# climatological_flows = ray.get(climatological_flows_id)
# climate_indices = ray.get(climate_indices_id)
# seasonal_forecasts = ray.get(seasonal_forecasts_id)
# Static_variables = ray.get(Static_variables_id)  
# extra_dict = ray.get(extra_dict_id)

                    
body_save_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/General_Head_Model/Hydra_Body_LSTM.pth'
head_save_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/General_Head_Model/Hydra_Head_LSTM.pth'
basin_heads_save_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/Basin_Head_Model'
                            
loss_path = f'/data/Hydra_Work/{Day}_Day_No_Forecast_Validation_Models_Seperate/{test_year}/General_Head_Model/Hydra_LSTM_loss.txt'

val_loss = 1000


if not os.path.exists(loss_path):
    # If the file does not exist, create it and write val_loss to it
    with open(loss_path, 'w') as file:
        file.write('%f' % val_loss)


copies = 1
warmup = 0

basin = 'animas_r_at_durango'
basins = [basin]


Use_Upstream = True
additional_data = None
if Use_Upstream:
    additional_data = extra_dict[basin]
        
        
additional_specific_head_hindcast_input_size = 1
if Use_Upstream:
    additional_specific_head_hindcast_input_size = 2
            


best_val_loss = 100
device = torch.device('cuda' if torch.cuda.
                is_available() else 'cpu')


general_head_learning_rate = 1e-3
Hydra_Bodys, General_Hydra_Heads, model_heads, optimizers, schedulers, general_optimizers, general_schedulers, specific_optimizers, specific_schedulers  = define_models_hydra(body_hindcast_input_size, body_forecast_input_size, 16,
                            64, 1, 0, 
                            32, 1, 3, 0, False, basins,
                            general_head_learning_rate, 1e-3, 1e-3, LR, additional_specific_head_hindcast_input_size = additional_specific_head_hindcast_input_size, device = device
                            )

In [32]:
Hydra_Bodys = {}
for copy in range(copies):
    Hydra_Bodys[copy] = torch.load(body_save_path) 

batch_size = 128
                                            
general_losses, specific_losses, general_val_losses, specific_val_losses, val_losses = [], [], [], [], []

# Initialise, with dummy scheduler
for copy in range(copies):
    # Initialise
    dummy_scheduler = lr_scheduler.StepLR(general_optimizers[copy],step_size = warmup, gamma = 0.8)

    Model_Run(Train_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
        Static_variables, additional_data, general_optimizers[copy], general_schedulers, criterion, early_stopper= None, n_epochs= warmup,
        batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, feed_forcing = False)

# Would be great if I could initialise the specific heads with the general heads, or finetune the specific heads at the end
        
for epoch in range(total_epochs):
    train_general_losses = {}
    train_specific_losses = {}
    train_climate_losses = {}
    epoch_val_general_losses = {}
    epoch_val_specific_losses = {}
    climate_losses = {}
    
    for copy in range(copies):
                    

        # Training General Head and Body
        # train_general_losses[copy], train_specific_losses[copy], train_climate_losses[copy] = Model_Run(Train_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
        #     Static_variables, additional_data, general_optimizers[copy], general_schedulers[copy], criterion, early_stopper= None, n_epochs= n_epochs,
        #     batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, feed_forcing = False)

        # Just tuning specific heads
        train_general_losses[copy], train_specific_losses[copy], train_climate_losses[copy] = Model_Run(Train_Dates, basins, Hydra_Bodys[copy], General_Hydra_Heads[copy], model_heads[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
            Static_variables, additional_data, specific_optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs= n_epochs,
            batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, feed_forcing = False)

NameError: name 'config' is not defined

In [19]:
results_df = results.get_dataframe()

In [23]:
results_df[results_df['val_loss'] < -0.77][['val_loss', 'config/body_learning_rate', 'config/head_learning_rate']]

    val_loss  config/body_learning_rate  config/head_learning_rate
0  -0.797797                      0.010                      0.010
1  -0.818613                      0.001                      0.010
2  -0.792372                      0.010                      0.001
3  -0.783051                      0.001                      0.001
8  -0.773321                      0.010                      0.010
10 -0.814937                      0.010                      0.001

In [20]:
results_df

,val_loss,timestamp,checkpoint_dir_name,done,training_iteration,trial_id,date,time_this_iter_s,time_total_s,pid,...,config/body_learning_rate,config/head_hidden_size,config/head_num_layer,config/head_dropout,config/head_learning_rate,config/spec_multiplier,config/batch_size,config/test_year,config/warmup,logdir
0,-0.760783,1722413689,None,False,29,6fc4a_00000,2024-07-31_08-14-49,31.490905,1074.879677,376925,...,0.0100,32,1,0.0,0.0100,1,128,2000,0,6fc4a_00000
1,-0.356441,1722413687,None,False,29,6fc4a_00001,2024-07-31_08-14-47,38.177503,1073.063103,376949,...,0.0001,32,1,0.0,0.0100,1,128,2000,0,6fc4a_00001
2,-0.804611,1722413710,None,False,53,6fc4a_00002,2024-07-31_08-15-10,20.794880,1095.473746,376955,...,0.0100,32,1,0.0,0.0001,1,128,2000,0,6fc4a_00002
3,-0.430616,1722413697,None,False,40,6fc4a_00003,2024-07-31_08-14-57,19.934380,1082.489232,376961,...,0.0001,32,1,0.0,0.0001,1,128,2000,0,6fc4a_00003
4,-0.776394,1722413489,None,False,37,6fc4a_00004,2024-07-31_08-11-29,18.178602,877.213556,376966,...,0.0100,32,1,0.0,0.0100,1,128,2002,0,6fc4a_00004
5,-0.282829,1722413699,None,False,32,6fc4a_00005,2024-07-31_08-14-59,35.257877,1085.882791,377163,...,0.0001,32,1,0.0,0.0100,1,128,2002,0,6fc4a_00005
6,-0.633017,1722413712,None,False,5,6fc4a_00006,2024-07-31_08-15-12,35.790044,191.284410,377440,...,0.0100,32,1,0.0,0.0001,1,128,2002,0,6fc4a_00006

# General Model with flags

In [ ]:

LR = 1e-3
static_size = np.shape(static_variables)[1]
forecast_size = np.shape(seasonal_forecasts['american_river_folsom_lake_2000_apr'])[1]
History_Fourier_in_forcings = 0 #2*3*(6 - 1)
Climate_guess = 0 #3
History_Statistics_in_forcings = 0 #5*2

forecast_input_size = forecast_size + static_size + History_Fourier_in_forcings + History_Statistics_in_forcings  + Climate_guess + 3
output_size, head_hidden_size, head_num_layers =  3, 64, 3
hindcast_input_size = 23 #8 for no flow without new data, 26 for flow with new, 25 for no flow with new

In [ ]:
import ray
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper

# Fixed parameters
total_epochs = 200
n_epochs = 1 # Epochs between tests
group_lengths = [1] # 
batch_size = 64
copies = 1

# parameters to tune
# I tuned to 128,2,0.4,False,1e-3 
hidden_sizes = [64]
num_layers = [2]
dropout = [0.1] # 0.2 0.4 both equal
bidirectional =  [False]
learning_rate = [1e-3]
batch_size = [128] 
p = [0.5]

config_space = {
    "hidden_size": tune.grid_search(hidden_sizes),
    "num_layers": tune.grid_search(num_layers),
    "dropout": tune.grid_search(dropout),
    "bidirectional": tune.grid_search(bidirectional),
    "learning_rate": tune.grid_search(learning_rate),
    "batch_size": tune.grid_search(batch_size),
    "p": tune.grid_search(p),
    'test_year': tune.grid_search(list(np.arange(2000,2024,2)) )
    
}


# Places to save info
model_dir = '/data/Hydra_Work/Post_Rodeo_Work/Tuned_General_Model/'

In [ ]:
def train_model_general_with_flag(config):
    
    All_Dates = ray.get(All_Dates_id)  
    
    years = list(np.arange(2000,2024,2))
    test_year = config['test_year']
    val_years = [years[years.index(test_year)-1], years[years.index(test_year)-2]  ]
    train_years = [year for year in years if year not in [test_year] + val_years]
    
    Test_Dates = All_Dates[All_Dates.year == test_year]
    Val_Dates = All_Dates[All_Dates.year.isin(val_years)]
    Train_Dates = All_Dates[All_Dates.year.isin(train_years)]
    
    era5 = ray.get(era5_id)  
    daily_flow = ray.get(daily_flow_id)  
    climatological_flows = ray.get(climatological_flows_id)
    climate_indices = ray.get(climate_indices_id)
    seasonal_forecasts = ray.get(seasonal_forecasts_id)
    Static_variables = ray.get(Static_variables_id)

    copies = 1
    
    
    device = torch.device('cuda' if torch.cuda.
                    is_available() else 'cpu')

    day = 1

    save_path = f'/data/Hydra_Work/{day}_Day_No_Forecast_Validation_Models/{test_year}/Flag_LSTM_Model/Flag_LSTM.pth'
    loss_path = f'/data/Hydra_Work/{day}_Day_No_Forecast_Validation_Models/{test_year}/Flag_LSTM_Model/Flag_LSTM.txt'

    val_loss = 1000
    
    
    if not os.path.exists(loss_path):
        # If the file does not exist, create it and write val_loss to it
        with open(loss_path, 'w') as file:
            file.write('%f' % val_loss)
    
  
    models, params_to_optimize, optimizers, schedulers = define_models(hindcast_input_size, forecast_input_size,
    config["hidden_size"], config["num_layers"], config["dropout"],
    config["bidirectional"], config["learning_rate"], copies=copies, device = device)

    batch_size = config["batch_size"]
    p = config["p"]
    losses, val_losses = [], []

    for epoch in range(total_epochs):

        train_losses = {}
        epoch_val_losses = {}

        for copy in range(copies):

             # Need to fix the outputs of No_Body_Model_Run
            train_losses[copy], Climate_Loss = Indicator_LSTM_Run(Train_Dates, basins, models[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs=n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=True, device=device, specialised=False, p = p)
            epoch_val_losses[copy], Climate_Loss = Indicator_LSTM_Run(Val_Dates, basins, models[copy], era5, daily_flow, climatological_flows, climate_indices, seasonal_forecasts,
                Static_variables, optimizers[copy], schedulers[copy], criterion, early_stopper= None, n_epochs=n_epochs,
                batch_size=batch_size, group_lengths=group_lengths, Train_Mode=False, device=device, specialised=False, p = p)

        loss = np.mean(list(train_losses.values())) - Climate_Loss


        candidate_val_loss = ((np.mean(list(epoch_val_losses.values())).mean() - Climate_Loss)[0])/np.mean(Climate_Loss)
        val_loss = np.min([val_loss, candidate_val_loss ])
        
        # Check best loss so far for this model
        with open(loss_path, 'r') as file:
            # Read the entire contents of the file
            Overall_Best_Val_Loss = float(file.read())

        if val_loss < Overall_Best_Val_Loss:
            torch.save(models[0], save_path)

            with open(loss_path, 'w') as f:
                f.write('%f' % val_loss)

            
               
        ray.train.report({'val_loss' : val_loss})

        losses.append(loss)
        val_losses.append(candidate_val_loss)
        #print(val_losses)
        #print(candidate_val_loss)
        #print(loss/np.mean(Climate_Loss))
    return val_loss

In [ ]:
from ray import train, tune
import ray
from ray import tune
from ray.tune import CLIReporter
from ray.tune.schedulers import ASHAScheduler
from ray.tune.stopper import TrialPlateauStopper
from ray.tune.search.optuna import OptunaSearch
import optuna


ray.shutdown()
ray.init(runtime_env = { "env_vars":   {"PYTHONPATH": '/data/Hydra_Work/Competition_Functions/' } } )
         
All_Dates_id = ray.put(All_Dates)  
era5_id = ray.put(era5)  
daily_flow_id = ray.put(daily_flow)  
climatological_flows_id = ray.put(climatological_flows)
climate_indices_id = ray.put(climate_indices)
seasonal_forecasts_id = ray.put(seasonal_forecasts)
Static_variables_id = ray.put(static_variables)

plateau_stopper = TrialPlateauStopper(
    metric="val_loss",
    num_results = 20,
    grace_period=200,
    mode="min",
)


def objective(config):  
    device = torch.device('cuda' if torch.cuda.
                      is_available() else 'cpu')
    
    #print('Device available is', device)
    

    score = train_model_general_with_flag(config) # Have training loop in here that outputs loss of model
    return {"val_loss": score}


#, search_alg = optuna_search
# optuna_tune_config = tune.TuneConfig(scheduler=asha_scheduler)
# tune_config = tune.TuneConfig(scheduler=asha_scheduler)
run_config=train.RunConfig(stop= plateau_stopper)

2024-07-08 18:42:11,651	INFO worker.py:1724 -- Started a local Ray instance.

(raylet) [2024-07-08 19:57:11,766 E 53059 53059] (raylet) node_manager.cc:3024: 2 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: 820d676b2e7b698978bb8bbdaed43fce379f8c1c18992477758e6d87, IP: 136.156.133.98) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 136.156.133.98`
(raylet)
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

In [ ]:
runs = 12
# Without Optuna
tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 15/runs , "gpu": 1/runs }), param_space=config_space, run_config = run_config) 
# With Optuna
#tuner = tune.Tuner(tune.with_resources(tune.with_parameters(objective), resources={"cpu": 1, "gpu": 1/16}), param_space = optuna_config_space, tune_config = optuna_tune_config, run_config = run_config) 

results = tuner.fit()
# try get_best_checkpoint, or change val to be maximum of current val_loss and previous ones
best_config = results.get_best_result(metric="val_loss", mode="min").config
print(best_config)
file_path = f"/data/Hydra_Work/Tuning/Config_Text/General_Model_best_config.txt"

# Open the file in write mode and save the configuration
with open(file_path, "w") as f:
    f.write(str(best_config))

print("Best configuration saved to:", file_path)

RuntimeError: Caught unexpected exception: Task was killed due to the node running low on memory.
Memory on the node (IP: 136.156.133.98, ID: 820d676b2e7b698978bb8bbdaed43fce379f8c1c18992477758e6d87) where the task (actor ID: 4713caa8a2ed9a00bc4e590b01000000, name=ImplicitFunc.__init__, pid=54543, memory used=3.87GB) was running was 119.60GB / 125.89GB (0.950001), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: e0790358740c4d46233a9b4dc89c6d3dbbb27751d0e60be42125f221) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 136.156.133.98`. To see the logs of the worker, use `ray logs worker-e0790358740c4d46233a9b4dc89c6d3dbbb27751d0e60be42125f221*out -ip 136.156.133.98. Top 10 memory users:
PID	MEM(GB)	COMMAND
40393	63.08	/home/gbmc/.vscode-server/cli/servers/Stable-ea1445cc7016315d0f5728f8e8b12a45dc0a7286/server/node --...
43014	3.89	/home/gbmc/miniforge3/envs/Hydra_Code/bin/python -Xfrozen_modules=off -m ipykernel_launcher --f=/hom...
54539	3.87	ray::ImplicitFunc.train
54540	3.87	ray::ImplicitFunc.train
54535	3.87	ray::ImplicitFunc.train
54542	3.87	ray::ImplicitFunc.train
54543	3.87	ray::ImplicitFunc.train
54533	3.87	ray::ImplicitFunc.train
54534	3.87	ray::ImplicitFunc.train
54536	3.87	ray::ImplicitFunc.train
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.